name: yearn_api_dart
description: A wrapper around the Yearn API. Responses are Dart objects, allowing you to effortlessly query the information using dot notation.
version: 1.0.1
repository: https://github.com/0xdir/yearn_api_dart

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0